development:
  database: movie_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: 
  password:

test:
  database: movie_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: 
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: movie_production
#   pool: 5
#   username: movie_demo
#   password:
